### ISSUE TITLE
[EPIC] BlockSync Overhaul - Storage

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1099]
## Context
This EPIC is an entry point for the BlockSync Storage Overhaul efforts.
For deeper context, look at ADR document: #1037 

### Preliminary Work

- [x] #878 
- [x] #1100
- [x] #824 
- [x] #183 
- [x] #1239
- [x] #1101
- [ ] #1103 (Nice to have)

### EDS Serde

- [x] #1105
- [x] #1104
- [x] #1352
- [x] #1106

### EDSStore

- [x] #1107
- [x] #1108
- [x] #1109
- [x] #1115
- [x] #1110
- [x] #1111
- [x] #1112
- [x] #1116
- [x] #1114
- [x] #1113
- [x] #1361
- [x] #1427
- [x] #1428
- [x] #1509

### Reading DataByNamespace

- [x] #1117
- [x] #1118

### Bridge/Full Node Integration

- [x] #1424
- [x] #1422
- [x] #1423

###  Post Housekeeping/Optimizations

- [ ] #1119
- [ ] #2743
- [x] #1120
- [x] share: write doc.go to be Go Doc compliant
- [ ] #2742
- [ ] #2744
- [x] #1233
- [x] #1291 
- [x] https://github.com/celestiaorg/celestia-node/issues/2018
- [x] https://github.com/celestiaorg/celestia-node/issues/2424

### Related

- [ ] #1121
- [x] #1122

### BugFixes
An ongoing list of bugfixes that are discovered and fixed during the EPIC implementation:
- [x] https://github.com/celestiaorg/celestia-node/pull/1196
- [x] #1498
- [x] https://github.com/celestiaorg/celestia-node/issues/1514
