### ISSUE TITLE
State interaction tracking issue 

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#1198]
TODO: 
- [ ] https://github.com/celestiaorg/celestia-node/issues/569
- [x] https://github.com/celestiaorg/celestia-node/issues/570
- [ ] https://github.com/celestiaorg/celestia-node/issues/572

**Comment by renaynay** [comment]
I would say we don't need a tracking issue for this anymore as it's not an actively worked-on workstream. 

Merge workstream will engulf these issues anyway
