### ISSUE TITLE
[EPIC] BlockSync Overhaul - Networking

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1397]
## Context

This EPIC is an entry point for the BlockSync Networking Overhaul efforts and a continuation of #1099 
For deeper context, look at the ADR document: https://github.com/celestiaorg/celestia-node/pull/1326.

## Tasks

- [ ] Merge #1326 

#### `ShrEx/EDS`

- [x] #1416
- [x] #1417
- [x] #1418

#### `ShrEx/ND`

- [x] #1419
- [x] #1420
- [x] #1421

#### `ShrEx/Push`

- [x] #1432
- [x] #1433

#### `share.Getter`
- [x] #1563
- [x] #1488
- [x] #1692
- [x] #1489
- [x] #1490
- [x] #1491
- [x] #1492
- [x] #1535
- [x] #1666

#### Discovery

- [x] #1449

#### Availability

- [x] #1450
- [x] #1464
- [x] #1465

#### Listener

- [x] #1467

#### DASer

- [x] #1466

### Testing

- [ ] swamp: `GetEDS` test using polling for FN and LN
- [ ] swamp: `GetEDS` test using shrex/sub FN and LN
- [ ] testground: `GetEDS` tests over API

### Hardenings

- [ ] https://github.com/celestiaorg/celestia-node/issues/1663
- [x] #1771 
- [x] #1775 
- [x] https://github.com/celestiaorg/celestia-node/pull/1745
- [ ] #2745
- [ ] https://github.com/celestiaorg/celestia-node/issues/1635
- [x] https://github.com/celestiaorg/celestia-node/issues/1731
- [x] https://github.com/celestiaorg/celestia-node/pull/1738)
- [x] https://github.com/celestiaorg/celestia-node/issues/1780
- [ ] https://github.com/celestiaorg/celestia-node/issues/1781

### Reconstruction
- [ ] eds: `Retriever` requests all the quadrants at once, instead of one-by-one

### Bugs

- https://github.com/celestiaorg/celestia-node/issues/1779
