### ISSUE TITLE
RPC/API Improvements Tracking

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#1474]
# RPC/Autogen

## First stable version
- [x] https://github.com/celestiaorg/celestia-node/issues/1345
- [x] https://github.com/celestiaorg/celestia-node/issues/1358
- [x] #425
- [ ] Add reflect tests to ensure compliance with RPC requirements
	- [ ] Context always exists as first parameter
	- [ ] Two return types, both JSON serializable, second one is always err
- [ ] API module definitions should match specification in ADR
- [ ] update ADR with overview of architecture

### Nice to haves
- [x] blob module 
- [x] improve UX around generating auth token

## Hardening
- [x] https://github.com/celestiaorg/celestia-node/issues/1401
- [x] OpenRPC Schema generation improvements for autogenerated clients
- [x] CLI over RPC
- [ ] https://github.com/celestiaorg/celestia-node/issues/1276
- [ ] https://github.com/celestiaorg/celestia-node/issues/739
- [ ] #2420

# Gateway:
- [ ] https://github.com/celestiaorg/celestia-node/issues/739
- [ ] Add JWT auth to writes
- [x] #1184

# Refactorings:
- [x] https://github.com/celestiaorg/celestia-node/issues/1375
- [ ] nodebuilder: extract module names into consts and reuse those consts where possible(https://github.com/celestiaorg/celestia-node/issues/1176)
- [x] Researching alternatives to `Internal` fields in API structs for `go-jsonrpc`
- [x] https://github.com/celestiaorg/celestia-node/issues/1401

# General API endpoint improvements / feature requests
- [ ] `header.GetAt` endpoint
- [x] consider deprecating `header.GetRangeByHeight` in favour of `header.GetVerifiedRangeByHeight`
- [x] #1942

## Future considerations
- [ ] #2811 
- [x] #1143
- [ ] #1302
- [ ] #1144

**Comment by Wondertan** [comment]
We must find a way to add options to our APIs for optional things like fee prices, versioning, etc.
The canonical way of using functional patterns would not be compatible with our RPC autogen. Though there might be a brilliant way to make the functional pattern work with reflection, but it's not known nor implemented in the RPC lib.

As a simple step, I propose adding an optional structure to each method, requiring an option. That structure would contain all the optional fields of the method. This way is compatible with our RPC lib and should be easy to replicate on different languages.

**Comment by ramin** [comment]
going to close this as a stale/general tracking issue and let the requisite linked issues that remain open track the work, so as we reduce issue count we can rely less on these kind of big issues
