### ISSUE TITLE
share/p2p/peers: Peer manager hardening tracking issue

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#1716]
- [x] https://github.com/celestiaorg/celestia-node/issues/1731
- [x] [add debug logs](https://github.com/celestiaorg/celestia-node/pull/1738)
- [x] add GC for old / unwanted pools
- [ ] https://github.com/celestiaorg/celestia-node/issues/1780
              
Related to #1707

**Comment by walldiss** [comment]
Closing, because all issues are tracked in Blocksync Epic:https://github.com/celestiaorg/celestia-node/issues/1397
