### ISSUE TITLE
[EPIC] BlobModule

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1835]
## Context

So far, celestia-node has developed all the infrastructure and necessary components from the ground up to provide a secure and scalable DA network. Now, the time has come to create that DA module and its API basing, using which any application on top can put data, retrieve and verify its _availability_. We call this module ___BlobModule___.

## BlobModule API

Let's define the API for it. For simplicity and to follow our practice, we define it in Golang.

___NOTE:___ _The API is WIP and discussion towards it's finalization happens in https://github.com/celestiaorg/celestia-node/discussions/1829_

```go
// Blob represents any application-specific binary data that anyone can submit to Celestia.
type Blob struct {
	Namespace namespace.ID
	Data []byte
}

// Commit computes hash commitment of the Blob.
func (b *Blob) Commit() []byte

// BlobModule provides all necessary
type BlobModule interface {
	// Submit sends PFB transaction and reports the height it landed on.
	// Allows sending multiple Blobs atomically synchronously.
	// Uses default wallet registered on the Node.
	Submit(context.Context, Blob...) (height uint64, error)

	// Get retrieves all the blobs for given namespaces at the given height. 
	Get(context.Context, height uint64, namespace.ID...) ([]Blob, error)
	
	// Available checks whether the given hash commitment of a blob is available/included at the given height under a particular namespace.
   // Useful for light clients wishing to check the inclusion of the data.
	Available(context.Context, height uint64, namespace.ID, hash []byte]) (bool, error)
}
```

```[tasklist]
### Tasks
- [ ] https://github.com/celestiaorg/celestia-node/issues/1836
- [ ] https://github.com/celestiaorg/celestia-node/issues/1837
- [ ] https://github.com/celestiaorg/celestia-node/issues/1838
- [ ] https://github.com/celestiaorg/celestia-node/issues/1839
- [ ] https://github.com/celestiaorg/celestia-node/issues/1840
- [ ] https://github.com/celestiaorg/celestia-node/issues/1841
- [ ] https://github.com/celestiaorg/celestia-node/issues/1676
```

**Comment by vgonkivs** [comment]
* https://github.com/celestiaorg/celestia-node/pull/1870

**Comment by distractedm1nd** [comment]
I would suggest moving the rest of the open issues to #2287 and closing this, so that we only have one blob module epic open

**Comment by Wondertan** [comment]
Agreed. @vgonkivs, mind making the suggestion?

**Comment by vgonkivs** [comment]
Will move all tasks to the Hardening EPIC

**Comment by ramin** [comment]
closing as remaining tasks moved to "the hardening" workstream/epic https://github.com/celestiaorg/celestia-node/issues/2287
