### ISSUE TITLE
modblob: scaffold BlobModule and it's API

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1841]
## Overview

We must establish infrastructure for the new [BlobModule](https://github.com/celestiaorg/celestia-node/issues/1835).

```[tasklist]
### SubTasks
- [ ] Define API as outlined in [BlobModule](https://github.com/celestiaorg/celestia-node/issues/1835) after it's finalized. Which include mocking, etc.
- [ ] Define API proxy with relevant API permissions.
- [ ] Introduce `Blob` structure and implement `Commit` method over apps `CreateCommitment`
- [ ] Provide default implementation of the API: ___`Submit` method that uses `StateModule` and  `Get` and `Available` methods using `Getter` interface___
- [ ] Docs
```

## Refs

Depends on https://github.com/celestiaorg/celestia-node/issues/1838 and 
#1840

Optionally depends on https://github.com/celestiaorg/celestia-node/issues/1839
