### ISSUE TITLE
[EPIC] Bridge node stability + performance

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#1935]
- [ ] https://github.com/celestiaorg/celestia-node/issues/1933
- [x] https://github.com/celestiaorg/celestia-node/issues/1640
- [x] https://github.com/celestiaorg/celestia-node/issues/1930
- [x] https://github.com/celestiaorg/celestia-node/issues/1934
- [x] #1993

Related: 
- [x] https://github.com/celestiaorg/celestia-node/issues/1644
- [x] https://github.com/celestiaorg/celestia-node/issues/1992
