### ISSUE TITLE
[EPIC] shrex stability + performance

### ISSUE THREAD

**Issue by walldiss** [celestiaorg/celestia-node#2106]
### Shrex-nd:
 - [ ] https://github.com/celestiaorg/celestia-node/issues/2035
 - [ ] https://github.com/celestiaorg/celestia-node/issues/2044
 - [ ] https://github.com/celestiaorg/celestia-node/issues/2051
 - [ ] https://github.com/celestiaorg/celestia-node/issues/2066
 - [ ] https://github.com/celestiaorg/celestia-node/issues/2089

### Shrex-eds:
 - [ ] https://github.com/celestiaorg/celestia-node/issues/2077

### Non-critical:
 - [ ] https://github.com/celestiaorg/celestia-node/issues/1997
 - [ ] https://github.com/celestiaorg/celestia-node/issues/2016
 
 ### Action plan
  - [ ] Debug why amount of peers from discovery shrinks over time
  -  [ ] implement metrics for shrex server and shrex middleware
     - https://github.com/celestiaorg/celestia-node/pull/2095
  -  [ ] use peers discovered by shrexSub as full nodes in peer-manager
  -  [ ] https://github.com/celestiaorg/celestia-node/pull/2101
  -  [ ] https://github.com/celestiaorg/celestia-node/pull/1924
  
  ## Performance
  -  [ ] implement client side per peer rate-limiting in peer-manager
  -  [ ] implement jitter to peer cooldown in peer-manager
  -  [ ] https://github.com/celestiaorg/celestia-node/pull/2101
  -  [ ] https://github.com/celestiaorg/celestia-node/pull/1924
  - [ ] duplicate messages from shrex.Sub
  - [ ] replace floodSub in shrex.Sub by celestia.Messanger

**Comment by walldiss** [comment]
Outdated
