### ISSUE TITLE
swamp: Cleanussy

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#2131]
Taken from https://github.com/celestiaorg/celestia-node/pull/1548

**TODO**
- [ ] Finish cleaning for fraud and p2p swamp tests
- [ ] Prettify logic around bootstrap settings
- [ ] Prettify setting of discovery interval, potentially set them for every node in the bridge
- [ ] Dive deeper into the RemoveNode method of the swamp, which seems useless
- [ ] Stop listening to redundant addresses in swamp
