### ISSUE TITLE
[EPIC]: Blob Module hardening

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-node#2287]
As Blob Module has landed, there are some ways how to make it more efficient. This epic will contain all tasks for the Blob Module v1.

- [ ] Collect leafHashes to verify the inclusion of the blob at a particular height.
- [ ] Store the first share of the Blob in the blob's proof.
- [ ] Moved from the leafHashes to the subtree roots in proof verification.

**Comment by Wondertan** [comment]
What about optimizations rather than hardening?

**Comment by ramin** [comment]
@vgonkivs migrated remaining tasks from https://github.com/celestiaorg/celestia-node/issues/1835 here and closing
