### ISSUE TITLE
[EPIC] Telemetry tracking issue

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#260]
## Telemetry
We've started the telemetry integration process as outlined in #901, and this issue gathers all the sub-issues and/or PRs related to the integration/implementation process.

## Base(d)
Scaffolding for further integration

- [x] #663
- [ ] https://github.com/celestiaorg/celestia-node/pull/907
- [x] https://github.com/celestiaorg/celestia-node/issues/934
- [ ] #935
- [ ] #936
- [ ] #937
- [x] https://github.com/celestiaorg/celestia-node/issues/1003

## Metrics Integration Spots
Actual code points for us to monitor/measure/observe/etc

- [ ] https://github.com/celestiaorg/celestia-node/issues/639
- [ ] https://github.com/celestiaorg/celestia-node/issues/98
- [x] https://github.com/celestiaorg/celestia-node/issues/999
- [x] https://github.com/celestiaorg/celestia-node/issues/1040
- [ ] Uptime metric

## Tracing Integration Spots
- [ ] ipld: consider tracing for `GetShares`
- [ ] share: simple trace for Light (besides Full) Availability

**Comment by marbar3778** [comment]
this would be awesome!!

**Comment by Wondertan** [comment]
Proposing https://github.com/VictoriaMetrics/VictoriaMetrics

**Comment by cemozerr** [comment]
I'll try chew on this. It seems like geth's metrics package is a fork of the go-metrics package with prometheus support added. I'll try and integrate that to celestia-node.

LETS GET THAT MONITORING SETUP ONLINE

**Comment by liamsi** [comment]
Key metrics of the top off my head:
- measure sampling time
- measure BlockSync time (per block and in total from height h, where h could be 0/genesis) for full nodes
- header sync time
- ....

**Comment by renaynay** [comment]
@liamsi sync is different from DAS. sync is only header sync rather than the actual block reconstruction. That happens during DAS
