### ISSUE TITLE
[EPIC] Storage Pruning

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#2748]
Generated from #2033 and #2615. After discussion I can create the actual issues for the ones we want to keep, with the original descriptions from mustafa's issues. 

#OperationPruneDN

```[tasklist]
### Prerequisites
- [ ] #2730 
- [ ] #2726
```

```[tasklist]
### Minimum Viable Pruning
- [ ] LN sampling and FN data sync only within storage window
- [ ] Pruning of blocks + CAR indexes outside storage window
- [ ] Pruning of inverted index outside storage window
- [ ] Advertisement of pruning nodes over discovery
- [ ] Make pruning default (after period of experimentation with experimental flag?)
```

```[tasklist]
### StoragePruner
- [ ] Integration of StoragePruner into daser module
- [ ] Integration of StoragePruner into header module
- [ ] StoragePruner metrics
- [ ] StoragePruner RPC methods
```

```[tasklist]
### Namespaced Nodes
- [ ] Namespaced partial storage full nodes
- [ ] (stretch) implement equally-sharded partial storage nodes outside of the storage window
```
