### ISSUE TITLE
[MINI-EPIC] RPC Breaking Changes

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#2770]
We are planning a few breaking RPC changes (surprise surprise) so let's merge them into a feature branch to avoid bumping the API version multiple times.

```[tasklist]
### Tasks
- [ ] refactor(share/getter)!: Take header.ExtendedHeader instead of share.DataHash
- [ ] fix(rpc)!: Change all public methods to read
- [ ] fix(rpc)!: Apply permission changes from internal audit
- [ ] feat(header)!: Limit range amount in GetVerifiedRangeByHeight
- [ ] #2725 
- [ ] #2764
- [ ] #2759
```

**Comment by distractedm1nd** [comment]
Completed
