### ISSUE TITLE
nodebuilder | nodebuilder/p2p: Hardcode mainnet chainID, change defaults to point to mainnet 

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#2823]
```[tasklist]
### Tasks
- [x] Hardcode mainnet chainID + add bootstrappers
- [x] Change default to point to mainnet instead of mocha
- [x] Ensure node store path does not append the network name if it is mainnet (only for testnets / non-default nets), so node store should be `~/.celestia-light` for mainnet and `~/.celestia-light-mocha` for `mocha`
```

**Comment by renaynay** [comment]
Done
