### ISSUE TITLE
Shwap workstream tracking issue

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2971]
Tracking issue for the storage and sampling part of the new Shwap protocol. The list is extracted and adapted from [draft PoC](https://github.com/celestiaorg/celestia-node/pull/2675) TODO list.

## Storage(dirty)
- [x] ODSFile
	- [x] Storage Format with Header
	- [x] Support Row and Col axis reads from ODSFile
	- [x] Support for single share reads with proof from ODSFile
	- [x] Support getting namespace data per row with proofs 
	- [x] Measure size diff between ODSFile with previous CAR files.
	- [x] Lazy-cache implementations for proofs and recomputed/extended axises.
	- [x] InMemory implementation for testing
	- [x] Benchmarks for reconstructSome, full row encode (cauchy), full encode Leopard
	- [x] reconstructSome compatability by using direct reedsolomon codec
	- [x] extend reconstructSome on parity (klauspost repo)
	- [x] reuse large object by memory pool
	- [x] cache ods after first read 
	- [ ] Leopard based reconstructSome (**blocked**)
	- [x] thread safety
- [x] q1 + q4 File
	- [x] Base implementation
	- [x] Benchmarks for worst case scenario vs ODSFile
- [ ] Filestore(integration stage)
	- [x] ODSFile streaming (Write/Read)
	- [x] Create new Store
	- [x] Add index by height to Store
	- [x] update caching to work over new File
	- [x] Add caching to Store
	- [x] Add index by Height to Cache
	- [x] Blockstore over Store
	- [x] Thread-safety for store
	- [ ] Lock Store folder while in use
	- [x] Post-integration code cleanup of old storage.
	- [x] Prunning support
	- [x] Metrics
- [x] Filestore integration
	- [x] Update ShrEx/Nd protocol, client/server implementations
	- [x] Update ShrEx/Eds
	- [x] Update Store getter 
	- [x] update availability
- [ ] BEFP integration
	- [x] extract shareWithProof from byzantine package
	- [ ] rework befp construction to work over array of shares (new retriever integration)

## Sampling
- [x] Protocol Messages
	- [x] SampleID -> Sample - requests samples by share indecies
	- [x] AxisID -> Axis - requests halfs of axises
	- [x] DataID -> Data - requests namespace data per row 
	- [x] Codecs and Multihash codes with ID types conversion to CIDs
	- [x] Stateless Hashers
	- [x] Protobuf definitions
	- [x] Use heights instead of DataHash to identify block 
	- [x] Hash requested Axis roots to cut namespaces and shorten requests
	- [ ] ~Versioning and backwards compatibility with old protocol~
	- [x] Server should decide which sample proof to return
	- [x] Remove Colomn requests (AxisID -> RowID)
	- [x] Remove AxisHash from AxisID
- [ ] Integration
	- [x] IPLDv2 row based getter
		- [x] Getter should support requesting batch of shares by idx at once 
		- [x] Store only samples by default
		- [x] Bitswap Sessions 
	- [x] Retriever over v2 (IPLDv2 reconstruction getter) (assigned to @walldiss)
	- [x] Multiplexer for different shwap protocols (@walldiss))
	- [x] Metrics 
	- [ ] ~IPLDv2 Server over LN storage (blockservice)~ Will work as is 
	- [x] Migrate actual sampling logic over GetShares #2984 

## Testing
- [x] test shrex with new storage 
- [x] test shwap
- [x] test on large storage
- [x] design load tests
- [x] perform load tests

## Stretch Goals
- [ ] Protocol message for requesting range of shares
	- By extending SampleID with additional uint16 that defines the end idx of range
- [ ] Blob requests by commitements
	- BlobID{DataID, Comm} -> Blob{BlobShares, ProofsToSubroot}
- [ ] Requesting proofs only for some request types
- [ ] Reconsider DHT discovery.

## Storage(clean)
TBC

**Comment by Wondertan** [comment]
Closing this one as completed. The TODO completion is actual and needed points were migrated to hardening
