### ISSUE TITLE
repo: Define Node's repository to manage all on disk data

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#30]
## Goal
There are multiple things that Celestia Node needs to store:
* Configurations
* Crypto Keys(p2p/consensus)
* Peers
* Share blobs
* Block blobs
* State
* DHT entries(for routing)

With the purpose of encapsulation, sealing all on-disk footprint from Node let's introduce a Repository. It should manage the root directory, versioning, categorizing, and grouping of any generated or user data to be stored on disk.

## Actions
* [x] #65
* [x] Core Repository managing Core's config/keys/genesis (#81)
```go
	// Note that other things can be done later
	type core.Repository interface {
		Config() (Config, error)
		PutConfig(*Config)  error
	}
```
* [ ] Repository interface (#86)
```go
	type node.Repository interface {
		  Keystore() (keystore.Keystore, error)
		  Datastore() (datastore.Batching, error)
		  Core() (core.Repository, error)
	  
		  Config() (*Config, error)
		  PutConfig(*Config) error
	  
		  Path() string
		  Close() error
			    
		  // Optional
		  DiskUsage() (uint64, error)
		  SetAPI(string) error
		  GetAPI() (string, error)
	}
```
* [ ] Config saving/loading (#86)
* [ ] Datastore over badger (#86)
* [ ] Locking(no more than once instance of Node must use a Repo simultaneously) (#86)
* [ ] Various statistics, like disk usage

**Comment by liamsi** [comment]
Note that using "repository" is a term stemming from the IPFS-world.

Off the top of my head for celestia-node this means a directory containing:
- all configuration files
- all DB data (light and data store, potential peer stores)

**Comment by renaynay** [comment]
@Wondertan can you provide more information in the description of the issue pls

**Comment by Wondertan** [comment]
Oh, shoot 🔫, this fall out of my radar. Will add info today.

**Comment by renaynay** [comment]
Note from discussion call: 

```go
SetAPI(string) error
GetAPI() (string, error)
``` 	  

This is for discovering way to communicate/connect with daemon (the endpoint). 
`GetAPI()` will fail if the node is not running.
This stems from IPFS.

**Decision:** 
We will revisit this when we we get to a point where we need admin over `Node`. For now, we will remove `GetAPI / SetAPI` from the interface.

**Comment by liamsi** [comment]
For more context on API, see: https://github.com/ipfs/specs/blob/master/REPO_FS.md#api

**Comment by Wondertan** [comment]
Sheesh, that's not closed
