### ISSUE TITLE
Usability/DevUX Meta Issue

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#3335]
This issue collects smaller quirks with the current API/docs/CLI in one place. I will list them here and break them out into their own issues where it makes sense:

- [x] the comment here is wrong: https://github.com/celestiaorg/celestia-node/blob/f2b664f3abe5e76ed51e19305aa3489980a93692/blob/service.go#L113 (it only returns one blob; GetAll is what returns all blobs)
- [x] GetAll is confusing and edge-cases are under-specified: https://github.com/celestiaorg/celestia-node/issues/3292#issuecomment-2059313529
- [x] some examples in API docs are not representative; e.g. blob.Get returns a different commitment than requested (#3317 )
- [x] CLI: when looking at the for usage returned by `--help` encoding related guidance is often missing, eg. `celestia blob get [height] [namespace] [commitment] [flags]` should state which format the inputs are expected in (hex? base64?). The CLI help should be self-contained; currently one needs to e.g. look [here](https://docs.celestia.org/developers/node-tutorial) to know how to use this
- [x] CLI: namespaces are submitted as hex but returned base64 encoded (which is very confusing); example: 

``` 
celestia blob submit 0x42690c204d39600fddd3 0x676d                                                                                                                  
{
  "result": {
    "height": 1671475,
    "commitments": [
      "0MFhYKQUi2BU+U1jxPzG7QY2BVV1lb3kiU+zAK7nUiY="
    ]
  }
}
⋊> ~/G/celestia-node on main ⨯ celestia blob get-all 1671475  0x42690c204d39600fddd3                                                                                                               12:06:50
{
  "result": [
    {
      "namespace": "AAAAAAAAAAAAAAAAAAAAAAAAAEJpDCBNOWAP3dM=",
      "data": "0x676d",
      "share_version": 0,
      "commitment": "0MFhYKQUi2BU+U1jxPzG7QY2BVV1lb3kiU+zAK7nUiY=",
      "index": 531
    }
  ]
}
```

 - [x] CLI/API: the node daemon gets started with only one account and one can only submit PFBs from that single account; this does not reflect how people interact with chains using different wallets for different purposes (applies to e.g. `celestia blob submit` and a bunch of state related commands / rpcs) https://github.com/celestiaorg/celestia-node/issues/3295
 - [x] #3345
 - [ ] consumers of the API do not have sufficient control for retries on blob submission
 - [x] also related to the above: https://github.com/celestiaorg/celestia-node/issues/3164
 - [x] #3361
 - [x] API: Clarify `State.SubmitPayForBlob`  vs `Blob.Submit`: both methods are too similar and it's unclear when to use which (related: https://github.com/celestiaorg/celestia-node/pull/3349#issuecomment-2109995753)

**Comment by Bidon15** [comment]
# Should be populated in node somehow

## Blobstream APIs in node

https://github.com/celestiaorg/celestia-core/issues/1306

## Many Execution Environments to 1 DA Node

https://github.com/celestiaorg/celestia-app/issues/3259
https://github.com/celestiaorg/celestia-node/issues/3295
https://github.com/celestiaorg/celestia-node/discussions/3022

## Separation of endpoints for DA Node (RPC/GRPC)

https://github.com/celestiaorg/celestia-node/issues/2931

## JWT Secret Rotation

https://github.com/celestiaorg/celestia-node/issues/3293

**Comment by vgonkivs** [comment]
https://github.com/celestiaorg/celestia-node/pull/3537

**Comment by vgonkivs** [comment]
> also related to the above: https://github.com/celestiaorg/celestia-node/issues/3164

After the fix on the app the issue "invalid account sequence" gone.

**Comment by vgonkivs** [comment]
>  the comment here is wrong

https://github.com/celestiaorg/celestia-node/pull/3530

> GetAll is confusing and edge-cases are under-specified

https://github.com/celestiaorg/celestia-node/pull/3223

> some examples in API docs are not representative; e.g. blob.Get returns a different commitment than requested

https://github.com/celestiaorg/celestia-node/pull/3479

> CLI: when looking at the for usage returned by --help encoding related guidance is often missing, eg. celestia blob get [height] [namespace] [commitment] [flags] should state which format the inputs are expected in 
CLI: namespaces are submitted as hex but returned base64 encoded (which is very confusing); example:

https://github.com/celestiaorg/celestia-node/pull/3553
https://github.com/celestiaorg/celestia-node/pull/3537


> CLI/API: the node daemon gets started with only one account and one can only submit PFBs from that single account; this does not reflect how people interact with chains using different wallets for different purposes (applies to e.g. celestia blob submit and a bunch of state related commands / rpcs

https://github.com/celestiaorg/celestia-node/pull/3349

>  https://github.com/celestiaorg/celestia-node/issues/3345

https://github.com/celestiaorg/celestia-node/pull/3391

> API: Clarify State.SubmitPayForBlob vs Blob.Submit: both methods are too similar and it's unclear when to use which 

https://github.com/celestiaorg/celestia-node/pull/3349#issuecomment-2109995753

**Comment by liamsi** [comment]
As all issues here have been tackled I think it is good to close this one for now. If there is a list of new issues regarding the API, we should open a new meta issue. Massive shoutout to @vgonkivs for tackling all these 🙏🏼 ❤️ 🎉
