### ISSUE TITLE
Improve go docs in general

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#426]
Looking at the current go docs the following needs to be improved:
- [ ] larger packages need a doc.go (especially if it is meant to be used by others)
- [ ] each package needs a package description either way 
- [ ] some public methods are not documented at all; at least intended for external consumers to use MUST be documented (Example: `VerifyAdjacent` [celestia-node/verify.go at 26c5d722405b296b5930688cd140ef1d31001342 · celestiaorg/celestia-node](https://github.com/celestiaorg/celestia-node/blob/26c5d722405b296b5930688cd140ef1d31001342/service/header/verify.go#L9))

_Build a habit of browsing the documentation locally_ via: `godoc -http=:6060`. Do the docs looks sufficiently clear to you? If not, then please improve them.

Currently this shows just blank in between otherwise  documented go packages for instance 😱 

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/7441766/153515242-a83a1e9a-38d4-4332-a2fd-98bac68cf403.png">

**Comment by ramin** [comment]
going to close this as stale and not directly actionable/assignable to complete.
