### ISSUE TITLE
[EPIC] State interaction tracking issue

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#568]
This issue will serve as an overarching tracking issue for state interaction-related issues. 

- [ ] Implement `StateAccess` over P2P according to design described in the [state ADR](https://github.com/celestiaorg/celestia-node/blob/main/docs/adr/adr-004-state-interaction.md)
- [ ] Add unit test for `CoreAccess` once mock celestia-app [issue]()
- [ ] Implement balance verification as described [here](https://github.com/celestiaorg/celestia-node/pull/513)
- [ ] Implement `StateAccess` over local instance of application
