### ISSUE TITLE
[EPIC] DAS improvement tracking issue

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#632]
This issue tracks all DAS-related feature/improvement issues.

### TODO

- [x] https://github.com/celestiaorg/celestia-node/issues/427
- [x] https://github.com/celestiaorg/celestia-node/issues/554
- [x] https://github.com/celestiaorg/celestia-node/issues/180
- [x] https://github.com/celestiaorg/celestia-node/issues/601
- [x] https://github.com/celestiaorg/celestia-node/issues/504 --> depends on implementation of 180 + some sort of manual and/or automatic implementation of retry functionality
- [x] https://github.com/celestiaorg/celestia-node/issues/483

### Testing
- [x] https://github.com/celestiaorg/celestia-node/issues/422

### Still deciding whether necessary
- [x] https://github.com/celestiaorg/celestia-node/issues/335
