### ISSUE TITLE
[EPIC] e2e: Celestia network tests 

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#7]
### Celestia network tests roadmap

Before incentivised testnet, we should have a set of test plans that contain such scenarios:
- [x] PoC: testground is a viable option for further test automation to catch regressions on a e2e level 
  - #638 
- [x] K8s Infra Setup: 
   - https://github.com/celestiaorg/test-infra/issues/25
- [x] appkit: Finish app-validator story 
   - https://github.com/celestiaorg/test-infra/issues/24
- [x] plan 1: Big blocks 
   - https://github.com/celestiaorg/test-infra/issues/77
- [ ] plan 2: Benchmarking Bridge/Full nodes serving shares to Light Nodes
   - https://github.com/celestiaorg/test-infra/issues/83
- [ ] plan 3: Node download data by namespace
  - #602 (for plan 1/2)
- [ ] plan 4: Peer discovery (peers (quickly) find/discover each other) 
  - #649
- [ ] plan 5: Block recovery
  - https://github.com/celestiaorg/test-infra/issues/21, 
  - #600 
- [ ] plan 6: composition tests for sync scenarios
  - #647 
Nice to have: 
- [ ] plan 7: working out custom malicious app nodes to test out befp

### CI/CD
In order to put out the tests above into a regular run cadence/schedule we need to do the following: 

1. Polish/Harden out the set of tests that are used for experiments
2. Split tests by amount of instances and which test-plans are executed in different stages
3. Define the inbound requirements which triggers test runs (e.g. once a release candidate is released in either of the stack app/node/optimint) 
4. Implement a new github action for e2e/network runs
5. Store a bucket of output logs
6. Notification mechanism

**Comment by Wondertan** [comment]
This will be resolved with Swamp.

**Comment by adlerjohn** [comment]
Ref: #315

**Comment by liamsi** [comment]
Swamp PR was merged now but at least some of this was rather about e2e tests with more realistic networking instead of integration tests and mocked networks.

**Comment by Bidon15** [comment]
> @Bidon15 1 bridge (4MB) and 1k light nodes das it

Updated the issue description to reflect this upcoming test-plan

**Comment by Bidon15** [comment]
We will close this issue once we get manual work for BR ods 128
