### ISSUE TITLE
[EPIC] Celestia-Node API

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#944]
## Context

This issue supersedes and encompasses https://github.com/celestiaorg/celestia-node/issues/169, serving as the canonical tracking issue for work related to celestia-node API.

## Current design

Simple HTTP server with endpoints accessing certain methods mounted on the servemux. See [here](https://github.com/celestiaorg/celestia-node/tree/main/service/rpc).

## Desired design

An RPC client that provides modules based on the services provided by the node. 

## Goals

- [X] eliminate need for go-cnc and DALC
- [X] automated documentation of methods

## Issue breakdown

- [x] 1. Finish [ADR](https://github.com/celestiaorg/celestia-node/pull/506)
- [x] 2. #958
  - [x] #923 
  - [x] #1126
  - [x] #304
- [x] 3. #959
- [x] 4. #977
- [x] 5. #962
  - [x] #256
  - [x] #873
- [x] 6. #1174
  - [x] #1183
  - [x] #1188
- [X] 7. Complete RPC
  - [x] #1185
      - [x] #1303
      - [x] #1207 
      - [x] #1208 
  - [x] #1186
  - [x] #1187
- [X] 8. Auxiliary
  - [x] #1278
  - [x] #726
  - [x] #1286 
  - [x] #1287
  - [x] #1288 
  - [x] #1299

## Related issues
- [x] https://github.com/celestiaorg/celestia-node/issues/1076

**Comment by Bidon15** [comment]
Added #709 after grooming

**Comment by Wondertan** [comment]
Ok, so the main reason I would like to use JSON/Open RPC is the ability to do the following. Imagine we have a simplified DA interface:
```
type DataAvailability interface {
  GetByNamespace(context.Context, namespace.ID, Root) ([][]byte, error)
  SubmitData(context.Context, namespace.ID, [][]byte) Root 
}
```
and its implementation:
```
// implements actual logic to read and write from node network
type availabilityService struct {}

// performs network ops to get the data
func (availability) GetByNamespace(context.Context, namespace.ID, Root) ([][]byte, error) 
// sends PFD
func (availability) SubmitData(context.Context, namespace.ID, [][]byte) (Root, error) 
```
With Open/JSONRPC tooling we are aware of, we can do this:
```
server := jsonrpc.NewServer(...)
server.Register(new(DataAvailability), &availabilityService{})
server.Serve()
```
This is almost all you need to do to set up your own RPC server. The tooling parses the given interface and automagically setups the endpoint for each existing method.

Similarly on the client side:
```
client := jsonrpc.NewClient(serverAddr, new(DataAvailability))

client.GetByNamespace() // does request to the remote server instance of DataAvailabiliy interface and returns the results
```
Simple, powerful, and composable.

With regular Rest APIs there is a lot of boilerplate code that you cannot avoid. GRPC is somewhat similar to RPC, but it generates interfaces for you, which I personally hate. Interfaces have to be handwritten with care and succinctness and cohesionin mind

**Comment by renaynay** [comment]
🚀
